name: Publish IIS Web App Deployment Using WinRM

on:
  push:
    tags:
      - 'iiswebapp-*'
  workflow_dispatch:

env:
  node-version: 10
  extension-name: ms-vscs-rm.${{ github.ref_name }}.vsix # ref_name is the tag, specified in the release.

jobs:

  build:

    name: Build
    runs-on: windows-latest
    permissions:
      contents: write # Permissions to attcach the artifact to release assets.
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.target_commitish }} # Checkout the commit that used in the release.

    - name: Install Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}

    - name: Install Node Modules
      run: npm install

    - name: Install TFX CLI
      run: npm install -g tfx-cli

    - name: Build with Gulp
      run: gulp build

    - name: Package with Gulp
      run: gulp package
    
    - name: Get asset upload URL
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Extension as Release Asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: _package/IISWebAppDeploy/${{ env.extension-name }}
        asset_name: ${{ env.extension-name }}
        asset_content_type: application/octet-stream
        
    - name: Upload Extension as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: IISWebAppDeploy Extension Artifact
        path: _package/IISWebAppDeploy/${{ env.extension-name }}


